### PR TITLE
Avoid `Deno` namespace

### PR DESCRIPTION
**Pull request by wojpawlik**

### CODE REVIEW

**Review by KnorpelSenf — APPROVED** [review]
This successfully avoids the Deno namespace, but why is that needed?

**Comment by wojpawlik** [comment]
Consistency is just nice to have

**Comment by KnorpelSenf** [comment]
I don't really know what will be more consistent here, it looks to me like you're just increasing how much favour Node APIs over Deno APIs

**Comment by wojpawlik** [comment]
I'm happy to keep shrinking the Deno namespace shim; it's obsoleted by `node:` (except `Deno.noColor`).

**Comment by MKRhere** [comment]
@wojpawlik I just saw this PR

**Comment by KnorpelSenf** [comment]
I'm too tired of your continuous force-pushing to review this, I'll unsubscribe, sorry

**Pull request closed without merging**
